### ISSUE TITLE
Save sometimes fails

### ISSUE THREAD

**Issue by joshpc** [joshpc/RecordVault-Issues#8]
**Describe the bug**
Saving sometimes fails silently.

**To Reproduce**
*If you have information on how to reproduce this please let me know.*

**Expected behaviour**
* Saving should alert you of failures (i.e. if you end up offline)
* This should not cause an error or log you out

**Comment by Some-dudes-carpet** [comment]
**Describe the bug**
Made some changes to Session Report 5, in this order.
- Changed a few words.
- Created links to other articles, added relationships to them (5 in total).

Moved away from the page to another page, was prompted to save, clicked Save & Go. Came back to this page soon after, changes had not saved.

Page still showed me as logged in. Refreshed the page to make sure, and now was shown as logged out.

**To Reproduce**
Have not tried to reproduce, but am ~95% sure this is not a new issue.

**Expected behaviour**
Page to have saved changes.
Not be logged out.

**Comment by joshpc** [comment]
This should mostly be resolved -- please let me know if there are new issues
